### ISSUE TITLE
Bug: Combat arts used by Emelie show as [object Object]

### ISSUE THREAD

**Issue by Alignn** [CCDirectLink/cc-combat-art-level-extender#1]
![180293655-0fc0f056-e01b-4f4b-91fa-5aa33dd35180](https://user-images.githubusercontent.com/18351802/180793176-42674df8-8460-4e9c-831a-ecf996f5b043.jpg)

I first used this mod together with Xenons triblade mod, and encountered an issue which I initially thought was caused by that mod (I even [submitted an issue](https://github.com/XenonA7/xenons-triblader-mod/issues/5)): combat arts used by party members (or at least Emelie's early game arts, as I had started a new game) don't show the correct combat art name above the character when used. 

However I eventually narrowed it down to being caused by this mod.
I previously uninstalled and wiped the entire CrossCode folder before reinstalling both the game and the mods, and the issue goes away even with all the other mods active, just not this one. 
It looks kind of like a string not found error, but I tried switching from English to German (and restarting), and still had the issue.
Tried verifying files (and then reinstalling CCLoader), no change.

**Comment by ghost** [comment]
I'll take a look at it next week.

**Comment by ghost** [comment]
I didn't make a release but test if the fix works using download zip feature of Github.

**Comment by Alignn** [comment]
Tested, works now! Thanks for the quick fix 👍
